feat: sort migrations before applying
mycodeself/mongo-migrate-ts pull request #111
Opened 2024-05-22 13:21 UTC by sf0rman

# Problem Description

Migration files are not ordered by timestamp when running `up`-command which can cause ordering issues.

For example
Migration1: createCollection
Migration2: change stuff within collection

If not ordered, migration-stuff attempts to run first and fails due to dependency on Migration1 (or collection existing)
```
ExecuteMigrationError: MongoServerError: ns does not exist: db.collection
```

# Solution

When creating a migration file, we know that all class names end with a 13-digit timestamp (`./lib/commands/new.ts:57`) regardless of using a custom template or the default one.

We can therefore extract timestamp from className (last 13 digits of className) and sort migrations based on this before running migrations.

2024-07-13 06:28 UTC, matheusmelchiades approved these changes

2024-07-13 06:28 UTC, matheusmelchiades approved these changes
LGTM

2024-08-07 12:00 UTC, matheusmelchiades approved these changes

2024-08-12 11:00 UTC, matheusmelchiades commented
https://github.com/mycodeself/mongo-migrate-ts/issues/114

2024-08-13 22:22 UTC, mycodeself requested changes
Hi @sf0rman, thank you very much for your input.

I have simply made a change to compare the className as a string with `localeCompare` when sorting the migrations, This way we are not dependent on the format of the className which may change

2024-08-13 22:22 UTC, mycodeself commented on lib/commands/up.ts
> +      });
Can't we compare the complete className using `localeCompre` and not be dependent on the name format?

2024-08-13 22:22 UTC, mycodeself commented on lib/utils/timestamp.ts
> +      date.getMilliseconds()
What motivates this change?

2024-08-13 22:55 UTC, mycodeself commented on lib/commands/up.ts
> +      });
```suggestion
      .sort((a, b) => a.className.localeCompare(b.className));
```

2024-08-13 23:01 UTC, merged

2024-08-13 23:03 UTC, mycodeself commented
:tada: This PR is included in version 1.6.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/mongo-migrate-ts/v/1.6.1)
- [GitHub release](https://github.com/mycodeself/mongo-migrate-ts/releases/tag/v1.6.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: