feat: save relative migrations path and add command to fix existing absolute paths
mycodeself/mongo-migrate-ts pull request #123
Opened 2024-10-04 09:18 UTC by jdachtera

2024-10-04 09:20 UTC, jdachtera commented on README.md
> +  -h, --help           display help for command
this change came from the actual output of running the command

2024-10-04 10:51 UTC, jdachtera commented
@mycodeself, I've added a test and addressed the audit warnings that were causing the CI to fail. Please review the changes and let me know if there’s anything you'd like me to adjust :)

2025-04-30 22:33 UTC, mycodeself requested changes
Hey @jdachtera thank you a lot for your contribution.

I have just suggested a small change in the readme to make more clear is required to run the `fix-paths` command to migrate to version 2.x.x

2025-04-30 22:33 UTC, mycodeself commented on lib/commands/fixPaths.ts
> +
```suggestion

```

2025-04-30 22:33 UTC, mycodeself commented on README.md
> +To fix these migration entries in your database you can use the `fix-paths` command:
```suggestion
## Upgrading to version 2.x.x

In version 1.x.x, this package stored migration file paths as absolute paths. As a result, rollbacks could only be executed from the same machine that performed the original migration, or from another with an identical directory structure.

To address this limitation, version 2.x.x now uses paths relative to the migrationsDir.
To update existing migration entries in your database and ensure compatibility, you can run the `fix-paths` command:
```

2025-04-30 22:34 UTC, mycodeself approved these changes

2025-04-30 23:01 UTC, merged

2025-04-30 23:03 UTC, mycodeself commented
:tada: This PR is included in version 2.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/mongo-migrate-ts/v/2.0.0)
- [GitHub release](https://github.com/mycodeself/mongo-migrate-ts/releases/tag/v2.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: