fix(#32): cli does not require config if init has not ran yet
mycodeself/mongo-migrate-ts pull request #55
Opened 2022-02-06 16:39 UTC by Krispy2009

This PR fixes issue #32.

 In short, we can load the cli with or without config. If the cli is loaded without, then the only available command is to run `init` to generate the files the rest of the commands need.

2022-02-06 19:11 UTC, mycodeself requested changes
Thanks a lot for your contribution @Krispy2009

2022-02-06 19:11 UTC, mycodeself commented on bin/index.ts
> +} catch {
Do you think we could handle the error and print the message? I think it would be better to avoid silencing other possible errors.

2022-02-07 10:55 UTC, Krispy2009 commented
Hey @mycodeself, thanks for the quick review! Is this what you mean? 

I was thinking to wrap the whole `try... catch` thing in a function so that I can write tests for it. Didn't want to go overboard if you don't require it though 🙂

2022-02-12 12:42 UTC, mycodeself requested changes
Just export the `ConfigFileNotFoundError` from the `lib/errors/index.ts`

2022-02-12 12:42 UTC, mycodeself commented on lib/config.ts
> +import { ConfigFileNotFoundError } from './errors/ConfigFileNotFoundError';
export the `ConfigFileNotFoundError` in the `lib/errors/index.ts` and import from there.

2022-02-12 14:00 UTC, Krispy2009 commented
Done! Sorry I didn't notice it earlier!

2022-02-13 00:11 UTC, mycodeself approved these changes
Nice work, thanks for contributing!

2022-02-13 00:11 UTC, merged

2022-02-13 00:13 UTC, mycodeself commented
:tada: This PR is included in version 1.0.16 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/mongo-migrate-ts/v/1.0.16)
- [GitHub release](https://github.com/mycodeself/mongo-migrate-ts/releases/tag/v1.0.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: